
services:
  mysql:
    image: mysql:8.0
    container_name: bookshelf-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bookshelf_db
    ports:
      - "3307:3306"
    volumes:
      - bookshelf-db-data:/var/lib/mysql
    networks:
      - bookshelf-network

  backend:
    build: .
    container_name: bookshelf-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookshelf_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - bookshelf-network

  frontend:
    build: ../BOOKSHELF_FrontEnd
    container_name: bookshelf-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - bookshelf-network

volumes:
  bookshelf-db-data:

networks:
  bookshelf-network:
    driver: bridge